package com.verAuto.orderTracking.enums;

public enum WindowType {
    PARE_BRISE,
    DEFLECTEUR_AVANT_GAUCHE,
    DEFLECTEUR_AVANT_DROITE,
    VITRE_AVANT_GAUCHE,
    VITRE_AVANT_DROITE,
    VITRE_ARRIERE_GAUCHE,
    VITRE_ARRIERE_DROITE,
    CUSTAUDE_ARRIERE_GAUCHE,
    CUSTAUDE_ARRIERE_DROITE,
    LUNETTE_ARRIERE,
    LUNETTE_ARRIERE_GAUCHE,
    LUNETTE_ARRIERE_DROITE;
}
